import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { SqliteStore } from "../../core/store/sqlite-store.js";
import { registerInit } from "./init.js";
import { registerImportPrd } from "./import-prd.js";
import { registerList } from "./list.js";
import { registerShow } from "./show.js";
import { registerNext } from "./next.js";
import { registerUpdateStatus } from "./update-status.js";
import { registerStats } from "./stats.js";
import { registerContext } from "./context.js";
import { registerUpdateNode } from "./update-node.js";
import { registerDeleteNode } from "./delete-node.js";
import { registerSearch } from "./search.js";
import { registerRagContext } from "./rag-context.js";
import { registerDecompose } from "./decompose.js";
import { registerVelocity } from "./velocity.js";
import { registerAddEdge } from "./add-edge.js";
import { registerDependencies } from "./dependencies.js";
import { registerBulkUpdateStatus } from "./bulk-update-status.js";
import { registerCreateSnapshot, registerRestoreSnapshot, registerListSnapshots } from "./snapshot.js";
import { registerAddNode } from "./add-node.js";
import { registerDeleteEdge } from "./delete-edge.js";
import { registerListEdges } from "./list-edges.js";
import { registerExportGraph } from "./export-graph.js";
import { registerMoveNode } from "./move-node.js";
import { registerCloneNode } from "./clone-node.js";
import { registerExportMermaid } from "./export-mermaid.js";
import { registerReindexKnowledge } from "./reindex-knowledge.js";
import { registerSyncStackDocs } from "./sync-stack-docs.js";
import { registerValidateTask } from "./validate-task.js";
import { registerPlanSprint } from "./plan-sprint.js";

export function registerAllTools(server: McpServer, store: SqliteStore): void {
  registerInit(server, store);
  registerImportPrd(server, store);
  registerList(server, store);
  registerShow(server, store);
  registerNext(server, store);
  registerUpdateStatus(server, store);
  registerStats(server, store);
  registerContext(server, store);
  registerUpdateNode(server, store);
  registerDeleteNode(server, store);
  registerSearch(server, store);
  registerRagContext(server, store);
  registerDecompose(server, store);
  registerVelocity(server, store);
  registerAddEdge(server, store);
  registerDependencies(server, store);
  registerBulkUpdateStatus(server, store);
  registerCreateSnapshot(server, store);
  registerRestoreSnapshot(server, store);
  registerListSnapshots(server, store);
  registerAddNode(server, store);
  registerDeleteEdge(server, store);
  registerListEdges(server, store);
  registerExportGraph(server, store);
  registerMoveNode(server, store);
  registerCloneNode(server, store);
  registerExportMermaid(server, store);
  registerReindexKnowledge(server, store);
  registerSyncStackDocs(server, store);
  registerValidateTask(server, store);
  registerPlanSprint(server, store);
}
