#!/usr/bin/env node

/**
 * mcp-graph Skills Installer
 * Interactive CLI to install 35 graph-* skills for Claude Code, GitHub Copilot, or Codex CLI.
 * Zero external dependencies — uses only Node.js built-in modules.
 * Cross-platform: Windows, macOS, Linux.
 */

import { readFileSync, writeFileSync, mkdirSync, symlinkSync, copyFileSync,
         readdirSync, existsSync, unlinkSync, lstatSync } from "node:fs";
import { join, resolve, basename, dirname } from "node:path";
import { homedir } from "node:os";
import { createInterface } from "node:readline";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SKILLS_DIR = __dirname;
const SKILL_FILES = readdirSync(SKILLS_DIR)
  .filter(f => f.startsWith("graph-") && f.endsWith(".md"))
  .sort();

const rl = createInterface({ input: process.stdin, output: process.stdout });

function ask(question) {
  return new Promise(res => rl.question(question, res));
}

function log(msg) {
  process.stdout.write(msg + "\n");
}

function safeLink(src, dest) {
  try {
    if (existsSync(dest)) {
      const stat = lstatSync(dest);
      if (stat.isSymbolicLink() || stat.isFile()) unlinkSync(dest);
    }
    symlinkSync(resolve(src), dest);
    return "linked";
  } catch {
    copyFileSync(src, dest);
    return "copied";
  }
}

function safeCopy(src, dest) {
  if (existsSync(dest)) unlinkSync(dest);
  copyFileSync(src, dest);
  return "copied";
}

function ensureDir(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

// ── Platform installers ─────────────────────────────────────

function installClaudeCode(method) {
  const base = join(homedir(), ".claude", "skills");
  let count = 0;

  for (const file of SKILL_FILES) {
    const name = basename(file, ".md");
    const skillDir = join(base, name);
    ensureDir(skillDir);

    const src = join(SKILLS_DIR, file);
    const dest = join(skillDir, "SKILL.md");

    const action = method === "symlink" ? safeLink(src, dest) : safeCopy(src, dest);
    log(`  \u2713 ${name} (${action})`);
    count++;
  }

  return { count, dest: base };
}

function installGitHubCopilot() {
  const ghDir = join(process.cwd(), ".github");
  ensureDir(ghDir);

  const dest = join(ghDir, "copilot-instructions.md");
  const parts = [
    "# mcp-graph Skills Reference",
    "",
    "> Auto-generated by skills-graph/install.mjs",
    "> MCP tool references (mcp__mcp-graph__*) are specific to mcp-graph integration.",
    "",
  ];

  for (const file of SKILL_FILES) {
    const name = basename(file, ".md");
    const content = readFileSync(join(SKILLS_DIR, file), "utf-8");
    parts.push(`---\n\n<!-- skill: ${name} -->\n\n${content}\n`);
    log(`  \u2713 ${name}`);
  }

  writeFileSync(dest, parts.join("\n"), "utf-8");
  return { count: SKILL_FILES.length, dest };
}

function installCodexCLI(method) {
  const base = join(process.cwd(), ".agents", "skills");
  ensureDir(base);
  let count = 0;

  for (const file of SKILL_FILES) {
    const name = basename(file, ".md");
    const skillDir = join(base, name);
    ensureDir(skillDir);

    const src = join(SKILLS_DIR, file);
    const dest = join(skillDir, "SKILL.md");

    const action = method === "symlink" ? safeLink(src, dest) : safeCopy(src, dest);
    log(`  \u2713 ${name} (${action})`);
    count++;
  }

  return { count, dest: base };
}

// ── Main ────────────────────────────────────────────────────

async function main() {
  log("");
  log("\u{1F6E0}\uFE0F  mcp-graph Skills Installer");
  log(`   ${SKILL_FILES.length} skills available\n`);

  log("Select platform:");
  log("  1) Claude Code      (~/.claude/skills/)");
  log("  2) GitHub Copilot   (.github/copilot-instructions.md)");
  log("  3) Codex CLI        (.agents/skills/)");
  log("  4) All platforms");
  log("");

  const platformChoice = await ask("> ");
  const platforms = platformChoice.trim();

  if (!["1", "2", "3", "4"].includes(platforms)) {
    log("\nInvalid selection. Exiting.");
    rl.close();
    return;
  }

  let method = "symlink";
  if (platforms === "1" || platforms === "3" || platforms === "4") {
    log("\nSelect installation method:");
    log("  1) Symlink (recommended \u2014 auto-updates with git pull)");
    log("  2) Copy (standalone \u2014 no git dependency)");
    log("");

    const methodChoice = await ask("> ");
    method = methodChoice.trim() === "2" ? "copy" : "symlink";
  }

  log("");

  const results = [];

  if (platforms === "1" || platforms === "4") {
    log(`Installing ${SKILL_FILES.length} skills for Claude Code (${method})...`);
    const r = installClaudeCode(method);
    results.push({ platform: "Claude Code", ...r });
    log("");
  }

  if (platforms === "2" || platforms === "4") {
    log(`Installing ${SKILL_FILES.length} skills for GitHub Copilot...`);
    const r = installGitHubCopilot();
    results.push({ platform: "GitHub Copilot", ...r });
    log("");
  }

  if (platforms === "3" || platforms === "4") {
    log(`Installing ${SKILL_FILES.length} skills for Codex CLI (${method})...`);
    const r = installCodexCLI(method);
    results.push({ platform: "Codex CLI", ...r });
    log("");
  }

  log("\u2705 Installation complete!\n");
  for (const r of results) {
    log(`   ${r.platform}: ${r.count} skills \u2192 ${r.dest}`);
  }
  log("\n   Run /graph-prd to get started.\n");

  rl.close();
}

main().catch(err => {
  console.error("Error:", err.message);
  rl.close();
  process.exit(1);
});
