export { classifyComplexity, routeQuery, decomposeIntoSubQueries, computeStrategyPerformance } from './adaptive-router.js';
export type { QueryComplexity, StrategyName, RoutingDecision, SubQuery, StrategyPerformance } from './adaptive-router.js';
export { indexCapture } from './capture-indexer.js';
export type { CaptureIndexResult } from './capture-indexer.js';
export { indexChallengeReport, searchChallengeHistory } from './challenge-indexer.js';
export type { ChallengeReport } from './challenge-indexer.js';
export { chunkText, smartChunk } from './chunk-text.js';
export type { ChunkOptions, TextChunk } from './chunk-text.js';
export { mapCitations, buildCitedContext } from './citation-mapper.js';
export type { Citation, CitedContext } from './citation-mapper.js';
export { extractCitationRefs } from './citation-chain.js';
export type { CitationRef, KnowledgeSearchResult } from './citation-chain.js';
export { indexCodeAnalysis } from './code-context-indexer.js';
export type { CodeSymbolInput, ProcessFlowInput, CodeAnalysisInput, IndexResult } from './code-context-indexer.js';
export { detectCommunities, generateCommunitySummary, rebuildCommunities } from './community-summarizer.js';
export type { Community, CommunitySummaryResult } from './community-summarizer.js';
export { indexConstitution } from './constitution-indexer.js';
export type { ConstitutionPrincipleInput, ConstitutionIndexInput, ConstitutionIndexResult } from './constitution-indexer.js';
export { validateRetrievedResults, correctResults, verifyCrossReferences } from './corrective-rag.js';
export type { ValidationIssue, ValidationResult, CrossRefCheck } from './corrective-rag.js';
export { indexDecision } from './decision-indexer.js';
export type { DecisionInput } from './decision-indexer.js';
export { indexCachedDocs } from './docs-indexer.js';
export type { DocsIndexResult } from './docs-indexer.js';
export { EMBEDDING_DIM, generateEmbedding, generateEmbeddingBatch } from './embedding-generator.js';
export { EmbeddingStore } from './embedding-store.js';
export type { EmbeddingEntry, SimilarityResult } from './embedding-store.js';
export { extractKeywords, extractEntities, generateSummary, enrichChunk, enrichChunks } from './enrichment-pipeline.js';
export type { EnrichedChunk } from './enrichment-pipeline.js';
export { extractEntitiesFromText, extractRelationsFromText } from './entity-extractor.js';
export type { ExtractedEntity, ExtractedRelation } from './entity-extractor.js';
export { indexEntitiesForDoc, indexEntitiesForDocs, indexEntitiesForSource } from './entity-index-hook.js';
export { indexDocument, reindexAll, indexBatch } from './entity-indexer.js';
export type { IndexDocumentResult, ReindexResult } from './entity-indexer.js';
export { EntityStore } from './entity-store.js';
export type { EntitySubgraph } from './entity-store.js';
export { graphProximityScore, executionGraphSearch, findCommunityDocs, findByCommunity } from './graph-rag-strategy.js';
export type { GraphRagResult, GraphRagOptions, NodeCommunity, CommunitySearchResult } from './graph-rag-strategy.js';
export { cosineSimilarity, linearSearch, HNSWIndex } from './hnsw-index.js';
export type { HNSWConfig, SearchResult } from './hnsw-index.js';
export { indexJourneyMaps } from './journey-indexer.js';
export type { JourneyIndexResult } from './journey-indexer.js';
export { findDuplicates, findContradictions } from './knowledge-dedup.js';
export type { DuplicatePair, Contradiction } from './knowledge-dedup.js';
export { applyFeedback } from './knowledge-feedback.js';
export { linkBySharedContext, findCrossSourceContext } from './knowledge-linker.js';
export { pruneKnowledge } from './knowledge-pruner.js';
export type { PruneStrategy, PruneOptions, PruneResult } from './knowledge-pruner.js';
export { getSourceReliabilityWeight, calculateQualityScore, recordUsage, decayStaleKnowledge } from './knowledge-quality.js';
export { runSynthesisCycle } from './knowledge-synthesizer.js';
export type { SynthesisResult } from './knowledge-synthesizer.js';
export { indexMemories } from './memory-indexer.js';
export type { MemoryIndexResult } from './memory-indexer.js';
export { DEFAULT_RRF_WEIGHTS, PHASE_RRF_PRESETS, getRrfWeightsForPhase, reciprocalRankFusion, weightedReciprocalRankFusion, multiStrategySearch } from './multi-strategy-retrieval.js';
export type { RankedResult } from './multi-strategy-retrieval.js';
export { indexNodeAsKnowledge, removeNodeFromKnowledge, indexAllNodes } from './node-indexer.js';
export { meanPoolAndNormalize, isOnnxAvailable, getOnnxProvider } from './onnx-embeddings.js';
export type { EmbeddingProvider } from './onnx-embeddings.js';
export { computePPR } from './personalized-pagerank.js';
export type { PprInput, PprResult } from './personalized-pagerank.js';
export { PhaseBoostCache } from './phase-boost-cache.js';
export type { PhaseBoostCacheOptions, PhaseBoostCacheStats } from './phase-boost-cache.js';
export { PHASE_ORDER, PHASE_BOOST_WEIGHTS, PHASE_SOURCE_AFFINITY, getPhaseBoost, applyPhaseBoost, getDynamicPhaseBoost, getSourceAffinity, getAdjacentPhases } from './phase-metadata.js';
export { generateAndIndexPhaseSummary } from './phase-summary.js';
export type { PhaseSummaryResult } from './phase-summary.js';
export { deduplicateResults, rerankByKeywordOverlap, stitchAdjacentChunks, postRetrievalPipeline } from './post-retrieval.js';
export type { PostRetrievalOptions, PostRetrievalResult } from './post-retrieval.js';
export { indexPrdContent } from './prd-indexer.js';
export type { PrdIndexResult } from './prd-indexer.js';
export { QueryCache } from './query-cache.js';
export type { CacheOptions, CacheStats } from './query-cache.js';
export { expandQuery } from './query-expander.js';
export type { QueryExpansionConfig, QueryExpansionResult, DocRetriever } from './query-expander.js';
export { detectIntent, detectSourceFilter, understandQuery, decomposeQuery } from './query-understanding.js';
export type { QueryIntent, UnderstandingResult, EntityMatch, DecomposedQuery } from './query-understanding.js';
export { computeNdcg, computeRecall, computePrecision, computeMrr, generateEvalDataset, runEvalBenchmark } from './rag-eval.js';
export type { EvalQuery, EvalMetrics, EvalReport } from './rag-eval.js';
export { TfIdfVectorizer, indexNodeEmbeddings, indexAllEmbeddings, incrementalIndex, semanticSearch } from './rag-pipeline.js';
export { RagSemanticCacheLayer } from './rag-semantic-cache-layer.js';
export type { CacheHitResult } from './rag-semantic-cache-layer.js';
export { RagTracer } from './rag-trace.js';
export type { RagStageName, RagStageTrace, RagTrace } from './rag-trace.js';
export { applyRelevanceBoosts } from './relevance-boost.js';
export type { ScoredResult } from './relevance-boost.js';
export { RelevanceTracker } from './relevance-tracker.js';
export type { RequeryResult } from './relevance-tracker.js';
export { ResponseCache } from './response-cache.js';
export type { ResponseCacheOptions, ResponseCacheStats } from './response-cache.js';
export { SemanticCache } from './semantic-cache.js';
export type { SemanticCacheOptions } from './semantic-cache.js';
export { indexSifContent } from './siebel-indexer.js';
export type { SiebelIndexResult } from './siebel-indexer.js';
export { indexSkills } from './skill-indexer.js';
export type { SkillIndexResult } from './skill-indexer.js';
export { calculateSourceContributions, identifyUnderutilizedSources } from './source-contribution.js';
export type { TraceAggregation, SourceContribution, UnderutilizedSource } from './source-contribution.js';
export { indexSwaggerContent } from './swagger-indexer.js';
export type { SwaggerIndexResult } from './swagger-indexer.js';
export { TfIdfEmbeddingCache } from './tfidf-embedding-cache.js';
export type { EmbeddingCacheOptions, EmbeddingCacheStats } from './tfidf-embedding-cache.js';
export { generateBudgetReport } from './token-budget-tracker.js';
export type { BudgetZone, BudgetConsumer, BudgetReport } from './token-budget-tracker.js';
export { recordTokenSaving, getTokenSavingsReport } from './token-savings.js';
export type { ToolSavings, SavingsReport } from './token-savings.js';
export { indexTranslationEvidence } from './translation-indexer.js';
export type { TranslationEvidenceInput, TranslationIndexResult } from './translation-indexer.js';
export { indexAcValidationResult } from './validation-indexer.js';
export type { AcResult, ValidationInput } from './validation-indexer.js';
export { quantizeVector, dequantizeVector } from './vector-quantization.js';
export type { QuantizedVector } from './vector-quantization.js';
export { indexWsdlContent } from './wsdl-indexer.js';
export type { WsdlIndexResult } from './wsdl-indexer.js';
