/*!
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright © 2026 Diego Lima Nogueira de Paula
 *
 * This file is part of mcp-graph.
 *
 * mcp-graph is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License v3.0 or later, as published by
 * the Free Software Foundation. See LICENSE for the full terms.
 *
 * mcp-graph is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE.
 *
 * Commercial licenses are available — see COMMERCIAL.md.
 */

/**
 * Interface Scaffolder — turns an `interface` graph node into a TypeScript
 * skeleton file + failing test stubs (TDD red).
 *
 * Pure function: no file I/O — returns descriptors (path + content) for the
 * caller to persist. USER-CODE-START / USER-CODE-END blocks in existing
 * content are preserved verbatim across re-scaffolds.
 */

import { logger } from "../utils/logger.js";

// --- Types ---

export interface InterfaceMethod {
  readonly name: string;
  /** Parameter list without outer parentheses, e.g. `"order: Order, id: string"` */
  readonly params: string;
  /** Return type, e.g. `"Promise<void>"` */
  readonly returns: string;
  readonly description?: string;
}

export interface InterfaceSpec {
  readonly id: string;
  /** PascalCase interface identifier used in source */
  readonly name: string;
  readonly description?: string;
  readonly methods: readonly InterfaceMethod[];
}

export interface ScaffoldOptions {
  /** Output directory for the generated interface file (default: `src/core/generated/`) */
  readonly interfaceDir?: string;
  /** Output directory for the generated test file (default: `src/tests/scaffolder/`) */
  readonly testDir?: string;
  /** Existing interface file content — USER-CODE blocks are preserved across re-scaffold */
  readonly existingInterfaceContent?: string;
  /** Existing test file content — if present, the new test file is flagged `created: false` */
  readonly existingTestContent?: string;
}

export interface ScaffoldedFile {
  readonly path: string;
  readonly content: string;
}

export interface ScaffoldedInterfaceFile extends ScaffoldedFile {
  readonly preservedBlocks: readonly string[];
}

export interface ScaffoldedTestFile extends ScaffoldedFile {
  /** true iff no `existingTestContent` was supplied (scaffolder freshly creates this stub) */
  readonly created: boolean;
}

export interface ScaffoldInterfaceResult {
  readonly interfaceFile: ScaffoldedInterfaceFile;
  readonly testFile: ScaffoldedTestFile;
}

// --- Public API ---

const DEFAULT_INTERFACE_DIR = "src/core/generated";
const DEFAULT_TEST_DIR = "src/tests/scaffolder";

export function scaffoldInterface(
  spec: InterfaceSpec,
  options: ScaffoldOptions = {},
): ScaffoldInterfaceResult {
  const interfaceDir = options.interfaceDir ?? DEFAULT_INTERFACE_DIR;
  const testDir = options.testDir ?? DEFAULT_TEST_DIR;

  const preservedBlocks = options.existingInterfaceContent
    ? extractUserCodeBlocks(options.existingInterfaceContent)
    : new Map<string, string>();

  const interfaceContent = renderInterfaceFile(spec, preservedBlocks);
  const testContent = renderTestFile(spec, interfaceDir, testDir);

  logger.info("interface-scaffolder", {
    nodeId: spec.id,
    name: spec.name,
    methodCount: String(spec.methods.length),
    preservedBlocks: String(preservedBlocks.size),
  });

  return {
    interfaceFile: {
      path: joinPath(interfaceDir, `${spec.name}.ts`),
      content: interfaceContent,
      preservedBlocks: [...preservedBlocks.keys()],
    },
    testFile: {
      path: joinPath(testDir, `${spec.name}.test.ts`),
      content: testContent,
      created: options.existingTestContent === undefined,
    },
  };
}

// --- Rendering ---

function renderInterfaceFile(spec: InterfaceSpec, preservedBlocks: ReadonlyMap<string, string>): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by interface-scaffolder — edit only inside USER-CODE blocks.");
  if (spec.description) {
    lines.push(`// ${spec.description}`);
  }
  lines.push("");
  lines.push(`export interface ${spec.name} {`);
  for (const method of spec.methods) {
    if (method.description) {
      lines.push(`  /** ${method.description} */`);
    }
    lines.push(`  ${method.name}(${method.params}): ${method.returns};`);
  }
  lines.push("}");
  lines.push("");

  for (const [name, body] of preservedBlocks) {
    lines.push(`// USER-CODE-START:${name}`);
    if (body.length > 0) {
      lines.push(body);
    }
    lines.push(`// USER-CODE-END:${name}`);
    lines.push("");
  }

  return lines.join("\n");
}

function renderTestFile(spec: InterfaceSpec, interfaceDir: string, testDir: string): string {
  const importPath = relativeImportPath(testDir, interfaceDir, spec.name);
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by interface-scaffolder — failing stubs (TDD red).");
  lines.push("// Replace `.failing` with active tests as each method is implemented.");
  lines.push("");
  lines.push(`import { describe, it, expect } from "vitest";`);
  lines.push(`import type { ${spec.name} } from "${importPath}";`);
  lines.push("");
  lines.push(`describe("${spec.name}", () => {`);
  for (const method of spec.methods) {
    lines.push(`  it.failing("${method.name} — pending implementation", () => {`);
    lines.push(`    // TODO: exercise ${spec.name}.${method.name} — remove .failing once green.`);
    lines.push(`    const impl = null as unknown as ${spec.name};`);
    lines.push(`    expect(impl).toBeDefined();`);
    lines.push(`  });`);
  }
  lines.push("});");
  lines.push("");
  return lines.join("\n");
}

// --- USER-CODE block preservation ---

const USER_CODE_BLOCK_RE = /\/\/\s*USER-CODE-START:([A-Za-z0-9_.-]+)\s*\r?\n([\s\S]*?)\r?\n\s*\/\/\s*USER-CODE-END:\1\b/g;

function extractUserCodeBlocks(source: string): Map<string, string> {
  const blocks = new Map<string, string>();
  for (const match of source.matchAll(USER_CODE_BLOCK_RE)) {
    const name = match[1];
    const body = match[2];
    blocks.set(name, body);
  }
  return blocks;
}

// --- Path helpers (POSIX-style, deterministic) ---

function joinPath(dir: string, file: string): string {
  const normalizedDir = dir.replace(/\/+$/u, "");
  return `${normalizedDir}/${file}`;
}

function relativeImportPath(fromDir: string, toDir: string, baseName: string): string {
  const fromParts = fromDir.split("/").filter(Boolean);
  const toParts = toDir.split("/").filter(Boolean);

  let common = 0;
  while (common < fromParts.length && common < toParts.length && fromParts[common] === toParts[common]) {
    common++;
  }

  const upHops = fromParts.length - common;
  const ascend = upHops === 0 ? "./" : "../".repeat(upHops);
  const descend = toParts.slice(common).join("/");
  const prefix = ascend + (descend ? `${descend}/` : "");
  return `${prefix}${baseName}.js`;
}
