/*!
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright © 2026 Diego Lima Nogueira de Paula
 *
 * This file is part of mcp-graph.
 *
 * mcp-graph is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License v3.0 or later, as published by
 * the Free Software Foundation. See LICENSE for the full terms.
 *
 * mcp-graph is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE.
 *
 * Commercial licenses are available — see COMMERCIAL.md.
 */

/**
 * State Machine Scaffolder — converts a `state_machine` graph node into:
 *   1. A TypeScript reducer with exhaustive switch over all states/events
 *   2. A test matrix: every state × every transition = N×T `it()` cases
 *
 * Pure function: no file I/O. Returns descriptors for the caller to persist.
 * Re-scaffold diff: only new states/transitions are added to existing content.
 */

export interface StateMachineTransition {
  readonly event: string;
  readonly from: string;
  readonly to: string;
}

export interface StateMachineSpec {
  readonly id: string;
  readonly name: string;
  readonly states: readonly string[];
  readonly transitions: readonly StateMachineTransition[];
}

export interface StateMachineScaffoldOptions {
  readonly reducerDir?: string;
  readonly testDir?: string;
  readonly existingReducerContent?: string;
}

export interface ScaffoldedFile {
  readonly path: string;
  readonly content: string;
}

export interface ScaffoldDiff {
  readonly addedStates: string[];
  readonly addedTransitions: StateMachineTransition[];
}

export interface StateMachineScaffoldResult {
  readonly reducerFile: ScaffoldedFile;
  readonly testFile: ScaffoldedFile;
  readonly diff: ScaffoldDiff;
}

// ── Public API ─────────────────────────────────────────────────────────────

/** scaffoldStateMachine — auto-generated description placeholder. */
export function scaffoldStateMachine(
  spec: StateMachineSpec,
  options: StateMachineScaffoldOptions = {},
): StateMachineScaffoldResult {
  const reducerDir = options.reducerDir ?? "src/core/generated/";
  const testDir = options.testDir ?? "src/tests/scaffolder/";
  const slug = toKebab(spec.name);

  const diff = computeDiff(spec, options.existingReducerContent);

  const reducerContent = generateReducer(spec);
  const testContent = generateTestMatrix(spec, slug);

  return {
    reducerFile: { path: `${reducerDir}${slug}-reducer.ts`, content: reducerContent },
    testFile: { path: `${testDir}${slug}-reducer.test.ts`, content: testContent },
    diff,
  };
}

// ── Reducer generator ──────────────────────────────────────────────────────

function generateReducer(spec: StateMachineSpec): string {
  const machineName = spec.name;
  const stateUnion = spec.states.map(s => `"${s}"`).join(" | ");
  const eventNames = [...new Set(spec.transitions.map(t => t.event))];
  const eventUnion = eventNames.map(e => `"${e}"`).join(" | ");

  const stateCases = spec.states.map(state => {
    const validTransitions = spec.transitions.filter(t => t.from === state);
    const eventCases = validTransitions.map(t =>
      `      case "${t.event}": return "${t.to}";`,
    ).join("\n");

    return `    case "${state}":
      switch (event) {
${eventCases || "        // no valid transitions"}
        default: throw new InvalidTransitionError({ state, event });
      }`;
  }).join("\n");

  return `// AUTO-GENERATED by state-machine-scaffolder — do not edit manually
// Re-scaffold to regenerate. See state-machine-scaffolder.ts.

export type ${machineName}State = ${stateUnion};
export type ${machineName}Event = ${eventUnion};

export interface InvalidTransitionDetails {
  state: string;
  event: string;
}

export class InvalidTransitionError extends Error {
  constructor(public readonly details: InvalidTransitionDetails) {
    super(\`Invalid transition: "\${details.event}" not allowed in state "\${details.state}"\`);
    this.name = "InvalidTransitionError";
  }
}

/** reduce$ — auto-generated description placeholder. */
export function reduce${machineName}(
  state: ${machineName}State,
  event: ${machineName}Event | string,
): ${machineName}State {
  switch (state) {
${stateCases}
  }
}
`;
}

// ── Test matrix generator ──────────────────────────────────────────────────

function generateTestMatrix(spec: StateMachineSpec, slug: string): string {
  const machineName = spec.name;
  const importPath = `../../core/generated/${slug}-reducer.js`;

  const transitionMap = new Map<string, Map<string, string>>();
  for (const tVar of spec.transitions) {
    let inner = transitionMap.get(tVar.from);
    if (!inner) {
      inner = new Map();
      transitionMap.set(tVar.from, inner);
    }
    inner.set(tVar.event, tVar.to);
  }

  const testCases: string[] = [];
  for (const state of spec.states) {
    for (const transition of spec.transitions) {
      const { event } = transition;
      const validTo = transitionMap.get(state)?.get(event);
      const label = `${state} + ${event} (t:${transition.from}→${transition.to})`;
      if (validTo && transition.from === state) {
        testCases.push(
          `  it("should transition ${label} → ${validTo}", () => {\n` +
          `    expect(reduce${machineName}("${state}", "${event}")).toBe("${validTo}");\n` +
          `  });`,
        );
      } else {
        testCases.push(
          `  it("should throw InvalidTransitionError for ${label}", () => {\n` +
          `    expect(() => reduce${machineName}("${state}", "${event}")).toThrow(InvalidTransitionError);\n` +
          `  });`,
        );
      }
    }
  }

  return `// AUTO-GENERATED test matrix — ${spec.states.length} states × ${spec.transitions.length} transitions = ${testCases.length} cases
import { describe, it, expect } from "vitest";
import { reduce${machineName}, InvalidTransitionError } from "${importPath}";

describe("${machineName} reducer matrix", () => {
${testCases.join("\n\n")}
});
`;
}

// ── Diff computation ───────────────────────────────────────────────────────

function computeDiff(spec: StateMachineSpec, existingContent?: string): ScaffoldDiff {
  if (!existingContent) {
    return { addedStates: [], addedTransitions: [] };
  }

  const addedStates = spec.states.filter(
    s => !existingContent.includes(`case "${s}"`),
  );

  const addedTransitions = spec.transitions.filter(
    t => !existingContent.includes(`case "${t.event}": return "${t.to}"`),
  );

  return { addedStates, addedTransitions };
}

// ── Utilities ──────────────────────────────────────────────────────────────

function toKebab(name: string): string {
  return name
    .replace(/([A-Z])/g, (_, c) => `-${c.toLowerCase()}`)
    .replace(/^-/, "");
}
