/*!
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright © 2026 Diego Lima Nogueira de Paula
 */

/**
 * Project-wide trend snapshot — turned into a memory entry on demand
 * (CLI subcommand) or by an external scheduler (skill / cron).
 *
 * Reads the `feature_depth_baselines` table that finish_task keeps
 * populated, builds an aggregate view (avg score, quadrant
 * distribution, top movers, modules below floor), and writes a
 * markdown memory at workflow-graph/memories/feature-depth/trends/
 * week-YYYY-WW.md. Idempotent — same week overwrites prior snapshot.
 *
 * Rationale (Context-Driven Engineering): the AI agent makes better
 * architectural decisions when it has empirical history of the
 * project's quality trajectory, not just the current snapshot.
 */

import type Database from "better-sqlite3";
import { writeMemory } from "../memory/memory-reader.js";
import { createLogger } from "../utils/logger.js";
import type { Quadrant } from "./quadrant.js";

const log = createLogger({ layer: "core", source: "trend-memory.ts" });

export interface TrendSnapshot {
  readonly date: string; // YYYY-MM-DD
  readonly isoWeek: string; // YYYY-WNN
  readonly totalFiles: number;
  readonly avgScore: number;
  readonly quadrants: Record<Quadrant, number>;
  readonly modulesByAvg: Array<{ module: string; avgScore: number; files: number }>;
  readonly bottomFiles: Array<{ relPath: string; module: string; score: number }>;
}

/** ISO week number (e.g. "2026-W17"). */
export function isoWeekOf(date: Date): string {
  // Per ISO 8601: weeks start Monday; week 1 is the one with Jan 4.
  const target = new Date(Date.UTC(
    date.getUTCFullYear(),
    date.getUTCMonth(),
    date.getUTCDate(),
  ));
  const dayNum = target.getUTCDay() || 7;
  target.setUTCDate(target.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(target.getUTCFullYear(), 0, 1));
  const weekNum = Math.ceil(((target.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
  return `${target.getUTCFullYear()}-W${weekNum.toString().padStart(2, "0")}`;
}

interface BaselineRowSql {
  rel_path: string;
  module: string;
  score: number;
  quadrant: string;
}

/** Query the baselines table and roll up into a snapshot. */
export function buildTrendSnapshot(db: Database.Database, when: Date = new Date()): TrendSnapshot | null {
  let rows: BaselineRowSql[];
  try {
    rows = db
      .prepare(
        "SELECT rel_path, module, score, quadrant FROM feature_depth_baselines",
      )
      .all() as BaselineRowSql[];
  } catch (err) {
    log.warn("feature-depth:trend-query-failed", {
      error: err instanceof Error ? err.message : String(err),
    });
    return null;
  }

  if (rows.length === 0) return null;

  const quadrants: Record<Quadrant, number> = {
    MATURE: 0, SPECIALIZED: 0, SHALLOW: 0, INCIPIENT: 0,
  };
  const moduleAcc = new Map<string, { sum: number; count: number }>();
  let scoreSum = 0;

  for (const row of rows) {
    quadrants[row.quadrant as Quadrant] = (quadrants[row.quadrant as Quadrant] ?? 0) + 1;
    scoreSum += row.score;
    const mVar = moduleAcc.get(row.module) ?? { sum: 0, count: 0 };
    mVar.sum += row.score;
    mVar.count += 1;
    moduleAcc.set(row.module, mVar);
  }

  const modulesByAvg = Array.from(moduleAcc.entries())
    .map(([module, { sum, count }]) => ({ module, avgScore: sum / count, files: count }))
    .sort((a, b) => b.avgScore - a.avgScore);

  const bottomFiles = [...rows]
    .sort((a, b) => a.score - b.score)
    .slice(0, 10)
    .map((r) => ({ relPath: r.rel_path, module: r.module, score: r.score }));

  return {
    date: when.toISOString().slice(0, 10),
    isoWeek: isoWeekOf(when),
    totalFiles: rows.length,
    avgScore: scoreSum / rows.length,
    quadrants,
    modulesByAvg,
    bottomFiles,
  };
}

/** Render a snapshot as markdown for memory storage. */
export function renderTrendMarkdown(snap: TrendSnapshot): string {
  const lines: string[] = [];
  lines.push(`# feature-depth trend — ${snap.isoWeek}`);
  lines.push("");
  lines.push(`Snapshot taken: **${snap.date}**`);
  lines.push("");
  lines.push("## Summary");
  lines.push(`- Files tracked: **${snap.totalFiles}**`);
  lines.push(`- Avg score: **${snap.avgScore.toFixed(1)}**`);
  lines.push(`- Quadrants: MATURE ${snap.quadrants.MATURE} · SPECIALIZED ${snap.quadrants.SPECIALIZED} · SHALLOW ${snap.quadrants.SHALLOW} · INCIPIENT ${snap.quadrants.INCIPIENT}`);
  lines.push("");
  lines.push("## Top modules (by avg score)");
  for (const mVar of snap.modulesByAvg.slice(0, 10)) {
    lines.push(`- \`${mVar.module}\` — ${mVar.avgScore.toFixed(1)} (${mVar.files} files)`);
  }
  lines.push("");
  lines.push("## Bottom files (lowest score, prime targets)");
  for (const fVar of snap.bottomFiles) {
    lines.push(`- \`${fVar.relPath}\` — ${fVar.score.toFixed(1)}`);
  }
  lines.push("");
  lines.push("> Auto-generated by `mcp-graph` feature-depth trend snapshotter.");
  return lines.join("\n") + "\n";
}

/**
 * Build + write a trend memory. Idempotent per ISO week.
 * Returns the memory name for caller's logging.
 */
export async function writeTrendMemory(
  db: Database.Database,
  projectRoot: string,
  when: Date = new Date(),
): Promise<{ ok: boolean; memoryName?: string; reason?: string }> {
  const snap = buildTrendSnapshot(db, when);
  if (!snap) {
    return { ok: false, reason: "no baselines available — run finish_task on at least one task with touched files first" };
  }
  const memoryName = `feature-depth/trends/week-${snap.isoWeek}`;
  const content = renderTrendMarkdown(snap);
  try {
    await writeMemory(projectRoot, memoryName, content);
    return { ok: true, memoryName };
  } catch (err) {
    return { ok: false, reason: err instanceof Error ? err.message : String(err) };
  }
}
