/*!
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright © 2026 Diego Lima Nogueira de Paula
 *
 * Generate downloadable test-run reports in HTML, Markdown, and ALM-Octane
 * compatible XML. PDF is rendered by feeding the HTML back through the
 * harness via CDP `Page.printToPDF` — kept out of this module to avoid
 * pulling in a renderer.
 */

import type { HarnessRun } from "../../schemas/browser-harness.schema.js";

function escHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export interface ReportInput {
  run: HarnessRun;
  /** Map of step index → screenshot bytes (PNG) for embedding. Optional. */
  screenshots?: Map<number, Buffer>;
}

export function buildHtmlReport(input: ReportInput): string {
  const { run, screenshots } = input;
  const verdictColor = run.verdict === "pass" ? "#16a34a" : run.verdict === "fail" ? "#dc2626" : "#d97706";
  const stepsHtml = run.results.map((r) => {
    const planned = run.plan.find((p) => p.index === r.index);
    const png = screenshots?.get(r.index);
    const img = png
      ? `<img alt="step ${r.index} screenshot" src="data:image/png;base64,${png.toString("base64")}" style="max-width:100%;border:1px solid #e5e7eb;border-radius:6px;margin-top:8px"/>`
      : r.screenshotPath
        ? `<div style="color:#6b7280;font-size:12px">screenshot: ${escHtml(r.screenshotPath)}</div>`
        : "";
    const args = planned ? escHtml(JSON.stringify(planned.args)) : "{}";
    const expect = planned?.expect ? `<div><strong>expect:</strong> <code>${escHtml(planned.expect)}</code></div>` : "";
    const error = r.error ? `<div style="color:#dc2626"><strong>error:</strong> ${escHtml(r.error)}</div>` : "";
    return `
      <li style="border:1px solid #e5e7eb;border-radius:8px;padding:12px;margin:8px 0;background:${r.ok ? "#f0fdf4" : "#fef2f2"}">
        <div style="display:flex;justify-content:space-between;align-items:center">
          <h3 style="margin:0">#${r.index} ${escHtml(r.helper)} ${r.ok ? "✅" : "❌"}</h3>
          <span style="color:#6b7280;font-size:12px">${r.durationMs}ms</span>
        </div>
        <div style="font-size:13px;color:#374151"><code>${args}</code></div>
        ${expect}
        ${error}
        ${img}
      </li>`;
  }).join("");

  return `<!doctype html><html lang="en"><head>
<meta charset="utf-8"/>
<title>Browser Harness Run ${escHtml(run.id)}</title>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<style>body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;max-width:980px;margin:24px auto;padding:0 16px;color:#111827}</style>
</head><body>
<header>
  <h1>Browser Harness Run</h1>
  <div style="display:flex;gap:24px;flex-wrap:wrap;margin:12px 0">
    <div><strong>Run ID:</strong> <code>${escHtml(run.id)}</code></div>
    <div><strong>Verdict:</strong> <span style="color:${verdictColor};font-weight:600">${run.verdict.toUpperCase()}</span></div>
    <div><strong>Duration:</strong> ${run.durationMs}ms</div>
    <div><strong>Steps:</strong> ${run.results.length}</div>
    <div><strong>Created:</strong> ${new Date(run.createdAt).toISOString()}</div>
  </div>
  <p><strong>Prompt:</strong> ${escHtml(run.prompt)}</p>
</header>
<ol style="list-style:none;padding:0">${stepsHtml}</ol>
<footer style="color:#6b7280;font-size:12px;margin-top:24px">Generated by mcp-graph browser-harness</footer>
</body></html>`;
}

export function buildMarkdownReport(input: ReportInput): string {
  const { run } = input;
  const lines: string[] = [];
  lines.push(`# Browser Harness Run \`${run.id}\``);
  lines.push("");
  lines.push(`- **Verdict:** ${run.verdict.toUpperCase()}`);
  lines.push(`- **Duration:** ${run.durationMs}ms`);
  lines.push(`- **Steps:** ${run.results.length}`);
  lines.push(`- **Created:** ${new Date(run.createdAt).toISOString()}`);
  lines.push("");
  lines.push(`> ${run.prompt.replace(/\n/g, "\n> ")}`);
  lines.push("");
  lines.push("## Steps");
  for (const r of run.results) {
    const planned = run.plan.find((p) => p.index === r.index);
    lines.push("");
    lines.push(`### #${r.index} ${r.helper} ${r.ok ? "✅" : "❌"} (${r.durationMs}ms)`);
    if (planned) lines.push("- args: `" + JSON.stringify(planned.args) + "`");
    if (planned?.expect) lines.push("- expect: `" + planned.expect + "`");
    if (r.error) lines.push("- error: `" + r.error + "`");
    if (r.screenshotPath) lines.push(`- screenshot: \`${r.screenshotPath}\``);
  }
  return lines.join("\n");
}

/**
 * ALM-Octane test result XML. Octane accepts the same JUnit-style schema for
 * external test runs. Each helper step becomes a `<testcase>`. Verdict maps:
 *  - ok=true  → passed (no nested element)
 *  - ok=false → `<failure>` with the error message
 */
export function buildOctaneXml(input: ReportInput): string {
  const { run } = input;
  const failures = run.results.filter((r) => !r.ok).length;
  const totalSec = (run.durationMs / 1000).toFixed(3);
  const cases = run.results.map((r) => {
    const cls = `BrowserHarness.${escXml(r.helper)}`;
    const time = (r.durationMs / 1000).toFixed(3);
    const fail = r.ok
      ? ""
      : `<failure type="HarnessFailure" message="${escXml(r.error ?? "step failed")}">${escXml(r.error ?? "step failed")}</failure>`;
    return `    <testcase classname="${cls}" name="step_${r.index}_${escXml(r.helper)}" time="${time}">${fail}</testcase>`;
  }).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="browser-harness:${escXml(run.id)}" tests="${run.results.length}" failures="${failures}" errors="0" time="${totalSec}" timestamp="${new Date(run.createdAt).toISOString()}">
    <properties>
      <property name="prompt" value="${escXml(run.prompt)}"/>
      <property name="verdict" value="${run.verdict}"/>
      <property name="sessionId" value="${escXml(run.sessionId)}"/>
    </properties>
${cases}
  </testsuite>
</testsuites>
`;
}
