/*!
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright © 2026 Diego Lima Nogueira de Paula
 *
 * This file is part of mcp-graph.
 *
 * mcp-graph is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License v3.0 or later, as published by
 * the Free Software Foundation. See LICENSE for the full terms.
 *
 * mcp-graph is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE.
 *
 * Commercial licenses are available — see COMMERCIAL.md.
 */

/**
 * Issue Pattern Tracker — Steering Loop for Harness Engineering
 *
 * Tracks recurring issues detected by analyze modes and auto-suggests
 * .claude/rules/ entries when patterns cross a threshold (default: 3).
 *
 * Based on: "Harness Engineering for Coding Agent Users" (Böckeler, Thoughtworks 2026)
 * Concept: Cybernetic steering loop — feedforward rules from feedback signals.
 */

import type Database from "better-sqlite3";
import { now } from "../utils/time.js";
import { generateId } from "../utils/id.js";
import { createLogger } from "../utils/logger.js";

const log = createLogger({ layer: "core", source: "issue-pattern-tracker.ts" });

// ── Schema ──────────────────────────────────────────────

const CREATE_TABLE_SQL = `
  CREATE TABLE IF NOT EXISTS issue_patterns (
    id TEXT PRIMARY KEY,
    pattern_type TEXT NOT NULL UNIQUE,
    count INTEGER NOT NULL DEFAULT 1,
    first_seen TEXT NOT NULL,
    last_seen TEXT NOT NULL,
    suggested_rule TEXT,
    auto_generated INTEGER NOT NULL DEFAULT 0
  )
`;

// ── Rule Templates ──────────────────────────────────────

const RULE_TEMPLATES: Record<string, string> = {
  missing_ac: `# Rule: Acceptance Criteria Required
Every task must have at least 2 testable acceptance criteria before moving to in_progress.
Use Given-When-Then format with concrete values.`,

  status_skip: `# Rule: Enforce Status Flow
Tasks must follow the status flow: backlog → ready → in_progress → done.
Never skip statuses. Use update_status for each transition.`,

  orphan_node: `# Rule: No Orphan Nodes
Every task/subtask must have a parent (epic or task).
Use edge(relationType: "parent_of") to link orphan nodes.`,

  circular_dep: `# Rule: No Circular Dependencies
Dependencies must form a DAG (directed acyclic graph).
Before adding a dependency, verify it doesn't create a cycle.`,

  oversized_task: `# Rule: Atomic Task Decomposition
Tasks sized L or XL must be decomposed into smaller subtasks (S or M).
Each subtask should be completable in ≤ 2 hours.`,

  missing_description: `# Rule: Description Required
Every task must have a non-empty description explaining what needs to be done.
Include context, approach, and any constraints.`,

  missing_estimate: `# Rule: Estimation Required
Every task must have xpSize (XS/S/M/L/XL) or estimateMinutes set
before moving to in_progress.`,
};

// ── Types ───────────────────────────────────────────────

export interface IssuePattern {
  id: string;
  patternType: string;
  count: number;
  firstSeen: string;
  lastSeen: string;
  suggestedRule: string | null;
  autoGenerated: boolean;
}

export interface PatternStats {
  total: number;
  recurring: number;
}

export interface RuleSuggestion {
  patternType: string;
  count: number;
  suggestedRule: string;
  firstSeen: string;
  lastSeen: string;
}

// ── Tracker ─────────────────────────────────────────────

export class IssuePatternTracker {
  private db: Database.Database;
  private threshold: number;

  constructor(db: Database.Database, threshold: number = 3) {
    this.db = db;
    this.threshold = threshold;
    this.db.exec(CREATE_TABLE_SQL);
  }

  /**
   * Record an issue detection. Creates or increments the pattern.
   */
  recordIssue(patternType: string, _sourceNodeId: string): void {
    const timestamp = now();

    const existing = this.db
      .prepare("SELECT id, count FROM issue_patterns WHERE pattern_type = ?")
      .get(patternType) as { id: string; count: number } | undefined;

    if (existing) {
      const newCount = existing.count + 1;
      const rule = newCount >= this.threshold
        ? (RULE_TEMPLATES[patternType] ?? `# Rule: Fix recurring "${patternType}" issues\nThis pattern has been detected ${newCount} times. Add a rule to prevent it.`)
        : null;

      this.db
        .prepare("UPDATE issue_patterns SET count = ?, last_seen = ?, suggested_rule = ? WHERE id = ?")
        .run(newCount, timestamp, rule, existing.id);
    } else {
      const id = generateId("ipt");
      this.db
        .prepare("INSERT INTO issue_patterns (id, pattern_type, count, first_seen, last_seen, suggested_rule, auto_generated) VALUES (?, ?, 1, ?, ?, NULL, 0)")
        .run(id, patternType, timestamp, timestamp);
    }

    log.debug(`Issue pattern recorded pattern="${patternType}"`);
  }

  /**
   * Get a specific pattern by type.
   */
  getPattern(patternType: string): IssuePattern | null {
    const row = this.db
      .prepare("SELECT * FROM issue_patterns WHERE pattern_type = ?")
      .get(patternType) as {
        id: string;
        pattern_type: string;
        count: number;
        first_seen: string;
        last_seen: string;
        suggested_rule: string | null;
        auto_generated: number;
      } | undefined;

    if (!row) return null;

    return {
      id: row.id,
      patternType: row.pattern_type,
      count: row.count,
      firstSeen: row.first_seen,
      lastSeen: row.last_seen,
      suggestedRule: row.suggested_rule,
      autoGenerated: row.auto_generated === 1,
    };
  }

  /**
   * Get all tracked patterns, sorted by count descending.
   */
  getAllPatterns(): IssuePattern[] {
    const rows = this.db
      .prepare("SELECT * FROM issue_patterns ORDER BY count DESC")
      .all() as Array<{
        id: string;
        pattern_type: string;
        count: number;
        first_seen: string;
        last_seen: string;
        suggested_rule: string | null;
        auto_generated: number;
      }>;

    return rows.map((row) => ({
      id: row.id,
      patternType: row.pattern_type,
      count: row.count,
      firstSeen: row.first_seen,
      lastSeen: row.last_seen,
      suggestedRule: row.suggested_rule,
      autoGenerated: row.auto_generated === 1,
    }));
  }

  /**
   * Get all patterns that crossed the threshold — ready for rule suggestion.
   */
  getSuggestedRules(): RuleSuggestion[] {
    const rows = this.db
      .prepare("SELECT * FROM issue_patterns WHERE count >= ? AND suggested_rule IS NOT NULL ORDER BY count DESC LIMIT 5")
      .all(this.threshold) as Array<{
        pattern_type: string;
        count: number;
        suggested_rule: string;
        first_seen: string;
        last_seen: string;
      }>;

    return rows.map((row) => ({
      patternType: row.pattern_type,
      count: row.count,
      suggestedRule: row.suggested_rule,
      firstSeen: row.first_seen,
      lastSeen: row.last_seen,
    }));
  }

  /**
   * Get summary stats for the harness response.
   */
  getStats(): PatternStats {
    const total = (this.db
      .prepare("SELECT COUNT(*) as cnt FROM issue_patterns")
      .get() as { cnt: number }).cnt;

    const recurring = (this.db
      .prepare("SELECT COUNT(*) as cnt FROM issue_patterns WHERE count >= ?")
      .get(this.threshold) as { cnt: number }).cnt;

    return { total, recurring };
  }
}
