export { autoWireDependencies } from './auto-wiring.js';
export type { AutoWireRequest, MissingDependency, AutoWireResult } from './auto-wiring.js';
export { getSiebelBestPractices, getBestPracticesByCategory } from './best-practices.js';
export type { BestPracticeRule } from './best-practices.js';
export { simulateChange } from './change-simulator.js';
export type { ChangeAction, Severity, RiskLevel, ChangeProposal, AffectedObject, SimulationResult } from './change-simulator.js';
export { cloneAndAdapt } from './clone-adapt.js';
export type { CloneAdaptRequest, CloneAdaptResult } from './clone-adapt.js';
export { reviewSiebelCode } from './code-review.js';
export type { ReviewCategory, ReviewIssue, ReviewOptions, ScoreBreakdown, CodeReviewResult } from './code-review.js';
export { calculateComplexity } from './complexity-metrics.js';
export type { ComplexityLevel, ObjectMetrics, ComplexityResult } from './complexity-metrics.js';
export { buildComposerInstructions, createComposerResult } from './composer-automation.js';
export type { ComposerActionOptions, ComposerInstructions, ComposerStep } from './composer-automation.js';
export { enrichSifContext } from './context-enrichment.js';
export type { EnrichmentRequest, EnrichmentResult } from './context-enrichment.js';
export { analyzeCrossProjectDeps } from './cross-project-analyzer.js';
export type { CrossProjectDep, ProjectSummary, CrossProjectResult } from './cross-project-analyzer.js';
export { checkSiebelReady } from './definition-of-ready.js';
export type { ReadyCheckRequest, ReadyCheck, ReadyCheckResult } from './definition-of-ready.js';
export { analyzeSiebelImpact, findDependencyChain, detectCircularDeps } from './dependency-analyzer.js';
export type { DependencyPath, CircularDep } from './dependency-analyzer.js';
export { extractScriptReferences } from './escript-crossref.js';
export type { ScriptRefType, ScriptReference } from './escript-crossref.js';
export { generateEScript } from './escript-generator.js';
export type { EScriptGenerationRequest, ReferencedEntity, EScriptGenerationResult } from './escript-generator.js';
export { detectEscriptPatterns } from './escript-patterns.js';
export type { ScriptPattern, PatternDetectionResult } from './escript-patterns.js';
export { refactorEscript } from './escript-refactor.js';
export type { RefactorIssue, DiffLine, RefactorResult } from './escript-refactor.js';
export { suggestFields } from './field-suggestion.js';
export type { FieldSuggestionRequest, FieldSuggestion, FieldSuggestionResult } from './field-suggestion.js';
export { checkEnvironmentHealth } from './health-check.js';
export type { HealthStatus, HealthCheckOptions, HealthCheckResult } from './health-check.js';
export { generateIntegrationTests } from './integration-test-gen.js';
export type { IntegrationTestCase, IntegrationTestSuite } from './integration-test-gen.js';
export { mapLovDependencies } from './lov-mapper.js';
export type { LovDependent, LovTypeInfo, LovMapResult } from './lov-mapper.js';
export { DEPLOY_ORDER, buildMigrationPackage } from './migration-package.js';
export type { MigrationPackageRequest, LockConflict, DeployScript, CircularDepInfo, MigrationPackage } from './migration-package.js';
export { DEFAULT_RULE_SETS, validateNamingConventions } from './naming-convention-validator.js';
export type { PrefixRule, CaseRule, NamingException, NamingRuleSet, NamingViolation, NamingValidationResult } from './naming-convention-validator.js';
export { generateSiebelErd } from './object-erd.js';
export type { ErdColumn, ErdTable, ErdRelationship, ErdResult } from './object-erd.js';
export { detectOrphans } from './orphan-detector.js';
export type { OrphanClassification, OrphanObject, OrphanResult } from './orphan-detector.js';
export { analyzePatterns } from './pattern-analyzer.js';
export type { NamingPattern, RequiredPropertyPattern, FieldDistribution, PatternAnalysisResult } from './pattern-analyzer.js';
export { analyzeProfileAttrFlow } from './profileattr-flow.js';
export type { AttrRef, ProfileAttrInfo, ProfileAttrFlowResult } from './profileattr-flow.js';
export { buildRuntimeDeps } from './runtime-dep-builder.js';
export { scaffoldSiebelObjects } from './scaffold-generator.js';
export type { ScaffoldRequest, ScaffoldResult } from './scaffold-generator.js';
export { loadSiebelConfig, saveSiebelConfig, addEnvironment, removeEnvironment, findEnvironment } from './siebel-config.js';
export { buildSiebelObjectContext } from './siebel-context-builder.js';
export { boostSiebelResults } from './siebel-rag-booster.js';
export type { ScoredDoc, BoostedDoc } from './siebel-rag-booster.js';
export { validateSecurity, validatePerformance, validateMigrationReadiness } from './siebel-validators.js';
export type { SensitiveFieldHit, DangerousOperation, VisibilityIssue, LgpdReport, SecurityValidationResult, PerformanceIssue, PerformanceValidationResult, MigrationChecklistItem, HardcodedValue, MigrationReadinessResult } from './siebel-validators.js';
export { batchImportSifs } from './sif-batch-importer.js';
export type { BatchImportOptions, BatchImportError, BatchImportResult } from './sif-batch-importer.js';
export { assembleSifContext } from './sif-context-assembler.js';
export type { KnowledgeSummary, SifGenerationContext } from './sif-context-assembler.js';
export { diffSifObjects, formatDiffMarkdown } from './sif-diff.js';
export type { PropertyChange, ChildChanges, ObjectModification, SifDiffResult } from './sif-diff.js';
export { prepareSifGeneration, finalizeSifGeneration } from './sif-generator.js';
export { parseSifContent, parseSifFile } from './sif-parser.js';
export { escapeXmlValue, listTemplates, getTemplate, buildSifXml } from './sif-templates.js';
export type { SifTemplateChild, SifTemplateObject, SifTemplate } from './sif-templates.js';
export { convertSifToGraph } from './sif-to-graph.js';
export type { SifToGraphResult } from './sif-to-graph.js';
export { detectSimilarObjects } from './similarity-detector.js';
export type { SimilarityPair, SimilarityResult } from './similarity-detector.js';
export { learnTemplates } from './template-learner.js';
export type { LearnedProperty, LearnedTemplate } from './template-learner.js';
export { troubleshootSiebel } from './troubleshoot.js';
export type { TroubleshootRequest, TroubleshootCause, RelatedScript, ConfigIssue, TroubleshootResult } from './troubleshoot.js';
export { validateWsdlContract } from './wsdl-contract-validator.js';
export type { OperationValidation, ContractValidationResult } from './wsdl-contract-validator.js';
export { correlateWsdlWithObjects } from './wsdl-correlation.js';
export type { WsdlCorrelationMatch, WsdlCorrelationResult } from './wsdl-correlation.js';
export { generateWsdlDocumentation } from './wsdl-doc-generator.js';
export { parseWsdlContent } from './wsdl-parser.js';
export type { WsdlField, WsdlComplexType, WsdlMessagePart, WsdlMessage, WsdlOperation, WsdlPort, WsdlService, WsdlMetadata, WsdlParseResult } from './wsdl-parser.js';
export { generateSifFromWsdl } from './wsdl-to-sif.js';
export type { WsdlToSifOptions, WsdlToSifResult } from './wsdl-to-sif.js';
