/**
 * Templates for .claudeignore and .copilotignore files.
 * Both files share the same content — lean context philosophy:
 * zero auto-load, everything via MCP on-demand.
 *
 * Generated by: npx mcp-graph init
 */

import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import { logger } from "../utils/logger.js";

const IGNORE_TEMPLATE = `# ========================================
# LEAN CONTEXT (mcp-graph)
# Filosofia: zero auto-load, tudo on-demand via MCP
# Gerado por: npx mcp-graph init
# ========================================

# === DEPENDENCIAS ===
node_modules/

# === GIT / GITHUB ===
.git/
.gitattributes
.github/

# === BUILDS / COMPILADOS ===
dist/
build/
out/
.next/
.turbo/
.cache/
*.tsbuildinfo
*.js.map
*.d.ts.map

# === TESTES (usar mcp-graph context para navegar) ===
src/tests/
__tests__/
*.test.ts
*.test.tsx
*.spec.ts
*.spec.tsx
coverage/
test-results/
playwright-report/

# === LOGS ===
logs/
*.log

# === DOCS (mcp-graph serve como fonte de docs) ===
docs/
*.md
!CLAUDE.md

# === SCRIPTS / TEMPLATES / DATA ===
scripts/
templates/
data/

# === ARQUIVOS GERADOS ===
**/prisma/migrations/
**/prisma/generated/
**/types/generated/
**/*.generated.ts

# === AMBIENTE / SECRETS ===
.env*
*.env
!.env.example

# === TEMP / BACKUPS ===
**/uploads/
**/temp/
**/tmp/
*.backup
*.bak

# === IDE ===
.vscode/
.idea/
*.swp
*.swo
*~
.DS_Store

# === DADOS MCP / SQLITE ===
workflow-graph/
*.db
*.db-shm
*.db-wal

# === MIDIA / BINARIOS ===
*.mp4
*.pdf
*.zip
*.tar
*.gz
*.png
*.jpg
*.jpeg
*.gif
*.svg
*.ico
*.woff*
*.ttf

# === LOCKS ===
package-lock.json
yarn.lock
pnpm-lock.yaml

# === CACHE ===
.eslintcache
.husky/

# === CONFIGS (ler sob demanda) ===
**/tailwind.config.*
**/postcss.config.*
**/tsconfig*.json
**/eslint*
**/.prettier*
**/vitest.config.*
**/playwright.config.*
docker-compose*.yml
Dockerfile*

# === CLAUDE (exceto rules/) ===
.claude/skills/
.claude/plans/
.claude/docs/
.claude/data/
.claude/*.md
.claude/*.json
.claude/*.json.backup

# === ROOT NAO-ESSENCIAIS ===
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
release-please-config.json
`;

/**
 * Get the shared ignore template content.
 */
export function getIgnoreTemplate(): string {
  return IGNORE_TEMPLATE;
}

/**
 * Ensure .claudeignore exists. Does NOT overwrite existing files.
 */
export function ensureClaudeIgnore(projectDir: string): boolean {
  const filePath = path.join(projectDir, ".claudeignore");
  if (existsSync(filePath)) {
    logger.debug(".claudeignore already exists, skipping");
    return false;
  }
  writeFileSync(filePath, IGNORE_TEMPLATE, "utf-8");
  logger.info(".claudeignore created with lean context template");
  return true;
}

/**
 * Ensure .copilotignore exists. Does NOT overwrite existing files.
 */
export function ensureCopilotIgnore(projectDir: string): boolean {
  const filePath = path.join(projectDir, ".copilotignore");
  if (existsSync(filePath)) {
    logger.debug(".copilotignore already exists, skipping");
    return false;
  }
  writeFileSync(filePath, IGNORE_TEMPLATE, "utf-8");
  logger.info(".copilotignore created with lean context template");
  return true;
}
