/*!
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright © 2026 Diego Lima Nogueira de Paula
 *
 * This file is part of mcp-graph.
 *
 * mcp-graph is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License v3.0 or later, as published by
 * the Free Software Foundation. See LICENSE for the full terms.
 *
 * mcp-graph is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE.
 *
 * Commercial licenses are available — see COMMERCIAL.md.
 */

/**
 * Templates for .claudeignore and .copilotignore files.
 * Both files share the same content — lean context philosophy:
 * zero auto-load, everything via MCP on-demand.
 *
 * Generated by: npx mcp-graph init
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createLogger } from "../utils/logger.js";

const log = createLogger({ layer: "core", source: "ignore-templates.ts" });

export type IgnoreUpdateStatus = "created" | "updated" | "up-to-date";

export interface IgnoreUpdateResult {
  status: IgnoreUpdateStatus;
  message: string;
}

const IGNORE_TEMPLATE = `# ========================================
# LEAN CONTEXT (mcp-graph)
# Filosofia: zero auto-load, tudo on-demand via MCP
# Gerado por: npx mcp-graph init
# ========================================

# === DEPENDENCIAS ===
node_modules/

# === SIBLING REPOS / VENDORED FORKS ===
*-skills/
*-main/
*-pilot/
hermes-*
understand-*
vendor/

# === GIT / GITHUB ===
.git/
.gitattributes
.github/

# === BUILDS / COMPILADOS ===
dist/
build/
out/
.next/
.turbo/
.cache/
*.tsbuildinfo
*.js.map
*.d.ts.map

# === TESTES + COVERAGE (use mcp-graph context para navegar testes) ===
src/tests/
__tests__/
*.test.ts
*.test.tsx
*.spec.ts
*.spec.tsx
coverage/
test-results/
test-screenshots/
playwright-report/
.nyc_output/

# === LOGS ===
logs/
*.log

# === DOCS (mcp-graph serve como fonte de docs) ===
docs/
*.md
!CLAUDE.md
!README.md

# === SCRIPTS / TEMPLATES / DATA ===
scripts/
templates/
data/

# === ARQUIVOS GERADOS ===
**/prisma/migrations/
**/prisma/generated/
**/types/generated/
**/*.generated.ts

# === AMBIENTE / SECRETS ===
.env*
!.env.example

# === TEMP / BACKUPS ===
**/uploads/
**/temp/
**/tmp/
*.backup
*.bak

# === IDE ===
.vscode/
.idea/
*.swp
*.swo
*~
.DS_Store
Thumbs.db

# === DADOS MCP / SQLITE / GRAPH STORES ===
.mcp-graph/
ai-shadow/
workflow-graph/
*.db
*.db-shm
*.db-wal

# === MIDIA / BINARIOS ===
*.mp4
*.pdf
*.zip
*.tar
*.gz
*.png
*.jpg
*.jpeg
*.gif
*.svg
*.ico
*.woff*
*.ttf

# === LOCKS ===
package-lock.json
yarn.lock
pnpm-lock.yaml
bun.lockb

# === CACHE ===
.eslintcache
.husky/

# === CONFIGS (ler sob demanda) ===
**/tailwind.config.*
**/postcss.config.*
**/tsconfig*.json
**/eslint*
**/.prettier*
**/vitest.config.*
**/playwright.config.*
docker-compose*.yml
Dockerfile*

# === CLAUDE (exceto rules/) ===
.claude/skills/
.claude/plans/
.claude/docs/
.claude/data/
.claude/*.md
.claude/*.json
.claude/*.json.backup

# === ROOT NAO-ESSENCIAIS ===
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
release-please-config.json
`;

/**
 * Get the shared ignore template content.
 */
export function getIgnoreTemplate(): string {
  return IGNORE_TEMPLATE;
}

/**
 * Ensure .claudeignore exists. Does NOT overwrite existing files.
 */
export function ensureClaudeIgnore(projectDir: string): boolean {
  const filePath = path.join(projectDir, ".claudeignore");
  if (existsSync(filePath)) {
    log.debug(".claudeignore already exists, skipping");
    return false;
  }
  writeFileSync(filePath, IGNORE_TEMPLATE, "utf-8");
  log.info(".claudeignore created with lean context template");
  return true;
}

/**
 * Ensure .copilotignore exists. Does NOT overwrite existing files.
 */
export function ensureCopilotIgnore(projectDir: string): boolean {
  const filePath = path.join(projectDir, ".copilotignore");
  if (existsSync(filePath)) {
    log.debug(".copilotignore already exists, skipping");
    return false;
  }
  writeFileSync(filePath, IGNORE_TEMPLATE, "utf-8");
  log.info(".copilotignore created with lean context template");
  return true;
}

function updateIgnoreFile(filePath: string, label: string, dryRun?: boolean): IgnoreUpdateResult {
  const exists = existsSync(filePath);
  if (!exists) {
    if (!dryRun) {
      writeFileSync(filePath, IGNORE_TEMPLATE, "utf-8");
      log.info(`${label} created with lean context template`);
    }
    return { status: "created", message: `${label} created` };
  }
  const current = readFileSync(filePath, "utf-8");
  if (current === IGNORE_TEMPLATE) {
    return { status: "up-to-date", message: `${label} up-to-date` };
  }
  if (!dryRun) {
    writeFileSync(filePath, IGNORE_TEMPLATE, "utf-8");
    log.info(`${label} updated to latest template`);
  }
  return { status: "updated", message: `${label} updated` };
}

/**
 * Update .claudeignore — always rewrites to match the current template.
 * Use from `mcp-graph update` so template improvements reach existing projects.
 */
export function updateClaudeIgnore(projectDir: string, dryRun?: boolean): IgnoreUpdateResult {
  return updateIgnoreFile(path.join(projectDir, ".claudeignore"), ".claudeignore", dryRun);
}

/**
 * Update .copilotignore — always rewrites to match the current template.
 * Use from `mcp-graph update` so template improvements reach existing projects.
 */
export function updateCopilotIgnore(projectDir: string, dryRun?: boolean): IgnoreUpdateResult {
  return updateIgnoreFile(path.join(projectDir, ".copilotignore"), ".copilotignore", dryRun);
}
