/*!
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright © 2026 Diego Lima Nogueira de Paula
 *
 * This file is part of mcp-graph.
 *
 * mcp-graph is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License v3.0 or later, as published by
 * the Free Software Foundation. See LICENSE for the full terms.
 *
 * mcp-graph is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE.
 *
 * Commercial licenses are available — see COMMERCIAL.md.
 */

import { useState, useEffect } from "react";
import { AlertTriangle, BookOpen, ChevronDown, ChevronRight } from "lucide-react";

interface IssuePattern {
  id: string;
  patternType: string;
  count: number;
  firstSeen: string;
  lastSeen: string;
  suggestedRule: string | null;
  autoGenerated: boolean;
}

interface PatternsResponse {
  ok: boolean;
  patterns: IssuePattern[];
  stats: { total: number; recurring: number };
  threshold: number;
}

const PATTERN_LABELS: Record<string, string> = {
  missing_ac: "Missing AC",
  status_skip: "Status Skip",
  orphan_node: "Orphan Node",
  circular_dep: "Circular Dep",
  oversized_task: "Oversized Task",
  missing_description: "Missing Description",
  missing_estimate: "Missing Estimate",
};

function formatPatternLabel(patternType: string): string {
  return PATTERN_LABELS[patternType] ?? patternType.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export function IssuePatternTracker(): React.JSX.Element {
  const [data, setData] = useState<PatternsResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [expandedRules, setExpandedRules] = useState<Set<string>>(new Set());

  useEffect(() => {
    fetch("/api/v1/harness/patterns")
      .then((res) => res.json())
      .then((json) => setData(json as PatternsResponse))
      .catch((err) => setError(String(err)));
  }, []);

  if (error) {
    return <div className="text-red-400 text-sm p-4">Pattern tracker error: {error}</div>;
  }

  if (!data) {
    return <div className="text-gray-500 text-sm p-4">Loading issue patterns...</div>;
  }

  if (data.patterns.length === 0) {
    return (
      <div className="text-gray-400 text-sm p-4">
        No issue patterns detected yet. Patterns are tracked when DoD checks fail during finish_task.
      </div>
    );
  }

  const maxCount = Math.max(...data.patterns.map((p) => p.count), 1);
  const patternsWithRules = data.patterns.filter((p) => p.suggestedRule);

  function toggleRule(patternType: string): void {
    setExpandedRules((prev) => {
      const next = new Set(prev);
      if (next.has(patternType)) next.delete(patternType);
      else next.add(patternType);
      return next;
    });
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3 text-sm text-gray-400">
        <span>{data.stats.total} pattern{data.stats.total !== 1 ? "s" : ""} tracked</span>
        <span className="text-gray-600">|</span>
        <span className={data.stats.recurring > 0 ? "text-amber-400" : ""}>
          {data.stats.recurring} recurring (threshold: {data.threshold})
        </span>
      </div>

      <div className="space-y-2">
        {data.patterns.map((pattern) => {
          const isAboveThreshold = pattern.count >= data.threshold;
          const barColor = isAboveThreshold ? "#ef4444" : "#6b7280";
          const barWidth = Math.max((pattern.count / maxCount) * 100, 4);

          return (
            <div key={pattern.id} className="flex items-center gap-2 text-sm">
              {isAboveThreshold && (
                <AlertTriangle className="w-3.5 h-3.5 text-red-400 flex-shrink-0" aria-label="Above threshold" />
              )}
              {!isAboveThreshold && <div className="w-3.5 flex-shrink-0" />}
              <span className="w-36 text-gray-300 truncate">{formatPatternLabel(pattern.patternType)}</span>
              <div
                className="flex-1 h-2 bg-gray-700 rounded-full overflow-hidden"
                role="progressbar"
                aria-valuenow={pattern.count}
                aria-valuemin={0}
                aria-valuemax={maxCount}
                aria-label={`${formatPatternLabel(pattern.patternType)}: ${pattern.count} occurrences`}
              >
                <div
                  className="h-full rounded-full transition-all"
                  style={{ width: `${barWidth}%`, backgroundColor: barColor }}
                />
              </div>
              <span className="w-8 text-right text-gray-400 tabular-nums">{pattern.count}x</span>
            </div>
          );
        })}
      </div>

      {patternsWithRules.length > 0 && (
        <div className="pt-2 border-t border-gray-700 space-y-2">
          <div className="flex items-center gap-1.5 text-xs font-medium text-amber-400">
            <BookOpen className="w-3.5 h-3.5" />
            <span>Rule Suggestions ({patternsWithRules.length})</span>
          </div>
          {patternsWithRules.map((pattern) => {
            const isExpanded = expandedRules.has(pattern.patternType);
            return (
              <div key={pattern.patternType} className="rounded bg-gray-800/80 border border-gray-700">
                <button
                  type="button"
                  className="flex items-center gap-2 w-full px-3 py-2 text-left text-sm text-gray-300 hover:text-white transition-colors cursor-pointer"
                  onClick={() => toggleRule(pattern.patternType)}
                  aria-expanded={isExpanded}
                >
                  {isExpanded
                    ? <ChevronDown className="w-3.5 h-3.5 flex-shrink-0" />
                    : <ChevronRight className="w-3.5 h-3.5 flex-shrink-0" />}
                  <span>{formatPatternLabel(pattern.patternType)}</span>
                  <span className="ml-auto text-xs text-gray-500">{pattern.count}x</span>
                </button>
                {isExpanded && (
                  <div className="px-3 pb-3">
                    <pre className="text-xs text-gray-400 whitespace-pre-wrap font-mono leading-relaxed">
                      {pattern.suggestedRule}
                    </pre>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
