export { computeConfidence } from './confidence-scorer.js';
export type { ConfidenceInput, ConfidenceDecision, ConfidenceEvidence } from './confidence-scorer.js';
export { AutopilotController } from './autopilot-controller.js';
export type { AutopilotConfig, AutopilotDecision, AutopilotSession, EvaluateInput } from './autopilot-controller.js';
export { AutopilotBridge } from './autopilot-bridge.js';
export type { PhaseChangeResult } from './autopilot-bridge.js';
export { createCheckpoint, rollbackToCheckpoint } from './graph-rollback.js';
export type { GraphCheckpoint, RollbackResult } from './graph-rollback.js';
export { createShadowBranch, mergeShadowBranch, discardShadowBranch, getShadowBranchName } from './shadow-branch.js';
export type { ShadowBranchResult, MergeResult, DiscardResult } from './shadow-branch.js';
export { RecoveryOrchestrator } from './recovery-orchestrator.js';
export type { RecoveryConfig, RecoveryResult, RecoveryMetrics } from './recovery-orchestrator.js';
export { AutopilotRecoveryBridge } from './autopilot-recovery-bridge.js';
export type { AutopilotRecoveryResult } from './autopilot-recovery-bridge.js';
export { EscalationEmitter } from './escalation-emitter.js';
export type { EscalationEvent } from './escalation-emitter.js';
export { RecoveryMetricsStore } from './recovery-metrics-store.js';
export type { RecoveryMetricEntry, RecoveryMetricsSummary } from './recovery-metrics-store.js';
